// Mock dataset — 15 weekend-trip destinations.
// Numeric `price` and `rating` power Sorting; `vibe`/`pace`/`distance`/`budget`
// power Filtering, Search, and Personalized Recommendations.
export const DESTINATIONS = [
  {
    id: "pondicherry", name: "Pondicherry", region: "Tamil Nadu",
    tagline: "French quarters, quiet cafés, sea-facing promenades",
    description: "A pastel-coloured former French colony where narrow lanes, courtyard cafés and a long sea promenade make for an easy, walkable weekend.",
    images: ["https://picsum.photos/seed/pondy-1/900/700", "https://picsum.photos/seed/pondy-2/900/700"],
    vibe: ["chill", "culture"], pace: "slow", distance: "near", distanceLabel: "3–4 hr drive",
    budget: "mid", price: 6500, rating: 4.5, bestTime: "Oct – Feb",
    highlights: ["Walk White Town's mustard-and-white lanes at sunrise", "Slow breakfast at a courtyard café on Rue Suffren", "Sunset on the Promenade"],
  },
  {
    id: "munnar", name: "Munnar", region: "Kerala",
    tagline: "Tea hills folded into mist, cool air, slow mornings",
    description: "Rolling tea estates and cool hill air make Munnar the go-to slow escape from the coastal heat, with short treks for those who want more.",
    images: ["https://picsum.photos/seed/munnar-1/900/700", "https://picsum.photos/seed/munnar-2/900/700"],
    vibe: ["chill", "adventure"], pace: "slow", distance: "medium", distanceLabel: "7–8 hr drive",
    budget: "mid", price: 8200, rating: 4.6, bestTime: "Sep – May",
    highlights: ["First light over the tea estates from Top Station", "Short trek to Kolukkumalai for sunrise above the clouds", "Evening by a wood stove"],
  },
  {
    id: "goa", name: "Goa", region: "Goa",
    tagline: "Beach shacks by day, music spilling out by night",
    description: "Two very different Goas in one trip: quiet South Goa mornings and North Goa nights that run late.",
    images: ["https://picsum.photos/seed/goa-1/900/700", "https://picsum.photos/seed/goa-2/900/700"],
    vibe: ["nightlife", "chill"], pace: "balanced", distance: "medium", distanceLabel: "1 hr flight",
    budget: "mid", price: 9500, rating: 4.4, bestTime: "Nov – Feb",
    highlights: ["Quiet swim at a South Goa beach in the morning", "Sunset drinks at a cliffside shack in Vagator", "Live music in Anjuna after dark"],
  },
  {
    id: "coorg", name: "Coorg", region: "Karnataka",
    tagline: "Coffee estates, waterfalls, forest trails underfoot",
    description: "Karnataka's coffee country — working estates, waterfalls a short walk apart, and food that leans spicy and slow-cooked.",
    images: ["https://picsum.photos/seed/coorg-1/900/700", "https://picsum.photos/seed/coorg-2/900/700"],
    vibe: ["chill", "adventure"], pace: "slow", distance: "medium", distanceLabel: "5–6 hr drive",
    budget: "mid", price: 7200, rating: 4.5, bestTime: "Oct – Mar",
    highlights: ["Coffee-picking walk through a working estate", "Cool off at Abbey Falls", "Dinner of Coorgi pandi curry"],
  },
  {
    id: "hampi", name: "Hampi", region: "Karnataka",
    tagline: "Ruined temples and boulder hills lit gold at dusk",
    description: "A UNESCO ruin-field of temples and boulders best explored slowly by bicycle, with a coracle ride to close the day.",
    images: ["https://picsum.photos/seed/hampi-1/900/700", "https://picsum.photos/seed/hampi-2/900/700"],
    vibe: ["culture", "adventure"], pace: "balanced", distance: "medium", distanceLabel: "8 hr drive / overnight train",
    budget: "budget", price: 4200, rating: 4.7, bestTime: "Oct – Feb",
    highlights: ["Cycle between temple ruins before the heat sets in", "Climb Matanga Hill for a 360° view", "Coracle ride at golden hour"],
  },
  {
    id: "alleppey", name: "Alleppey", region: "Kerala",
    tagline: "Backwaters, houseboats, and villages seen from water",
    description: "A houseboat weekend through palm-fringed backwaters — the slowest possible way to see a village go by.",
    images: ["https://picsum.photos/seed/alleppey-1/900/700", "https://picsum.photos/seed/alleppey-2/900/700"],
    vibe: ["chill"], pace: "slow", distance: "medium", distanceLabel: "9–10 hr drive",
    budget: "splurge", price: 14000, rating: 4.6, bestTime: "Nov – Feb",
    highlights: ["Drift through paddy-fringed canals on a houseboat", "Fresh karimeen for lunch, cooked on board", "Watch village life pass from the upper deck"],
  },
  {
    id: "wayanad", name: "Wayanad", region: "Kerala",
    tagline: "Caves, waterfalls, and misty ghat roads to explore",
    description: "Dense forest, prehistoric caves, and a heart-shaped lake at the top of a trek — Wayanad rewards an early start.",
    images: ["https://picsum.photos/seed/wayanad-1/900/700", "https://picsum.photos/seed/wayanad-2/900/700"],
    vibe: ["adventure"], pace: "packed", distance: "medium", distanceLabel: "6–7 hr drive",
    budget: "mid", price: 7800, rating: 4.3, bestTime: "Oct – May",
    highlights: ["Trek up to Chembra Peak for the heart-shaped lake", "Explore the prehistoric Edakkal Caves", "Spot wildlife on an early jeep safari"],
  },
  {
    id: "jaipur", name: "Jaipur", region: "Rajasthan",
    tagline: "Pink sandstone forts and markets that hum after dark",
    description: "Forts on every hill, bazaars that never quite close, and rooftop dinners looking back at all of it lit up.",
    images: ["https://picsum.photos/seed/jaipur-1/900/700", "https://picsum.photos/seed/jaipur-2/900/700"],
    vibe: ["culture", "nightlife"], pace: "packed", distance: "far", distanceLabel: "2 hr flight",
    budget: "mid", price: 9000, rating: 4.4, bestTime: "Oct – Mar",
    highlights: ["Sunrise climb to Nahargarh Fort", "Bargain for block-print textiles in Bapu Bazaar", "Rooftop dinner with Amer Fort lit up"],
  },
  {
    id: "rishikesh", name: "Rishikesh", region: "Uttarakhand",
    tagline: "River rapids by day, temple bells along the ghats by dusk",
    description: "White-water in the morning, riverside quiet by evening — Rishikesh runs at two very different speeds.",
    images: ["https://picsum.photos/seed/rishikesh-1/900/700", "https://picsum.photos/seed/rishikesh-2/900/700"],
    vibe: ["adventure", "chill"], pace: "balanced", distance: "far", distanceLabel: "2 hr flight + 1 hr drive",
    budget: "budget", price: 5200, rating: 4.5, bestTime: "Sep – Nov, Mar – May",
    highlights: ["Morning white-water rafting on the Ganges", "Quiet riverside yoga before the day heats up", "Evening Ganga Aarti at Triveni Ghat"],
  },
  {
    id: "gokarna", name: "Gokarna", region: "Karnataka",
    tagline: "Quieter beaches, cliff trails, low-key bonfire nights",
    description: "Goa's quieter cousin — cliff trails between coves, hammock afternoons, and bonfires instead of clubs.",
    images: ["https://picsum.photos/seed/gokarna-1/900/700", "https://picsum.photos/seed/gokarna-2/900/700"],
    vibe: ["chill", "nightlife"], pace: "slow", distance: "medium", distanceLabel: "9–10 hr drive",
    budget: "budget", price: 4800, rating: 4.4, bestTime: "Oct – Mar",
    highlights: ["Cliff walk between Om Beach and Half Moon Beach", "Afternoon nap in a beach-shack hammock", "Bonfire and guitars on the sand"],
  },
  {
    id: "udaipur", name: "Udaipur", region: "Rajasthan",
    tagline: "Lakes, palaces, and rooftop views at every turn",
    description: "A city built around its lakes, with a palace or a rooftop view around almost every corner.",
    images: ["https://picsum.photos/seed/udaipur-1/900/700", "https://picsum.photos/seed/udaipur-2/900/700"],
    vibe: ["culture", "chill"], pace: "balanced", distance: "far", distanceLabel: "2.5 hr flight",
    budget: "splurge", price: 13500, rating: 4.7, bestTime: "Sep – Mar",
    highlights: ["Boat ride on Lake Pichola at sunset", "Wander the City Palace complex", "Rooftop dinner facing the lake"],
  },
  {
    id: "manali", name: "Manali", region: "Himachal Pradesh",
    tagline: "Snow-line views, river valleys, mountain-town energy",
    description: "Old Manali's cafés and a short drive up to snow — a mountain-town weekend with something for both paces.",
    images: ["https://picsum.photos/seed/manali-1/900/700", "https://picsum.photos/seed/manali-2/900/700"],
    vibe: ["adventure", "nightlife"], pace: "packed", distance: "far", distanceLabel: "1.5 hr flight + 2 hr drive",
    budget: "mid", price: 8800, rating: 4.3, bestTime: "Mar – Jun, Oct – Feb",
    highlights: ["Drive up to Solang Valley for snow views", "Café-hop through Old Manali", "River-side bonfire at night"],
  },
  {
    id: "chikmagalur", name: "Chikmagalur", region: "Karnataka",
    tagline: "Misty coffee hills, waterfalls, quiet homestays",
    description: "Karnataka's coffee heartland — foggy mornings, a short peak trek, and homestays that feel like slowing down on purpose.",
    images: ["https://picsum.photos/seed/chikmagalur-1/900/700", "https://picsum.photos/seed/chikmagalur-2/900/700"],
    vibe: ["chill", "adventure"], pace: "slow", distance: "medium", distanceLabel: "5 hr drive",
    budget: "mid", price: 6800, rating: 4.5, bestTime: "Oct – Mar",
    highlights: ["Sunrise trek up Mullayanagiri", "Estate-stay coffee tasting", "Waterfall stop at Hebbe Falls"],
  },
  {
    id: "pushkar", name: "Pushkar", region: "Rajasthan",
    tagline: "Desert lake town, ghats, rooftop cafés at sundown",
    description: "A small desert town wrapped around a holy lake, with rooftop cafés that catch every sunset.",
    images: ["https://picsum.photos/seed/pushkar-1/900/700", "https://picsum.photos/seed/pushkar-2/900/700"],
    vibe: ["culture", "chill"], pace: "slow", distance: "far", distanceLabel: "2 hr flight + 1 hr drive",
    budget: "budget", price: 4500, rating: 4.2, bestTime: "Oct – Mar",
    highlights: ["Walk the ghats around Pushkar Lake at sunrise", "Browse the market for silver jewellery", "Rooftop café at sunset"],
  },
  {
    id: "andaman", name: "Havelock Island", region: "Andaman & Nicobar",
    tagline: "Turquoise water, coral reefs, barefoot island time",
    description: "An island weekend built around water — reef snorkels by day, barefoot dinners on the sand by night.",
    images: ["https://picsum.photos/seed/havelock-1/900/700", "https://picsum.photos/seed/havelock-2/900/700"],
    vibe: ["chill", "adventure"], pace: "balanced", distance: "far", distanceLabel: "2.5 hr flight + ferry",
    budget: "splurge", price: 17500, rating: 4.8, bestTime: "Nov – Apr",
    highlights: ["Snorkel the reef at Elephant Beach", "Sunset at Radhanagar Beach", "Barefoot dinner on the sand"],
  },
];
